FROM python:3.9

RUN apt-get update && \
    apt-get install -y tesseract-ocr \
    libtesseract-dev \
    tesseract-ocr-eng \
    tesseract-ocr-jpn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN tesseract --version

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .